# Generated by Django 4.0.4 on 2022-05-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_remove_employees_employee_name_user_employees_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
